# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(355, 300)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 70, 257, 55))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_FontBold = QtWidgets.QPushButton(self.groupBox)
        self.btn_FontBold.setCheckable(True)
        self.btn_FontBold.setAutoExclusive(False)
        self.btn_FontBold.setObjectName("btn_FontBold")
        self.horizontalLayout.addWidget(self.btn_FontBold)
        self.btn_FontItalic = QtWidgets.QPushButton(self.groupBox)
        self.btn_FontItalic.setCheckable(True)
        self.btn_FontItalic.setAutoExclusive(False)
        self.btn_FontItalic.setObjectName("btn_FontItalic")
        self.horizontalLayout.addWidget(self.btn_FontItalic)
        self.btn_FontUnderLine = QtWidgets.QPushButton(self.groupBox)
        self.btn_FontUnderLine.setCheckable(True)
        self.btn_FontUnderLine.setAutoExclusive(False)
        self.btn_FontUnderLine.setObjectName("btn_FontUnderLine")
        self.horizontalLayout.addWidget(self.btn_FontUnderLine)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 257, 55))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_AlignLeft = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_AlignLeft.setCheckable(True)
        self.btn_AlignLeft.setAutoExclusive(True)
        self.btn_AlignLeft.setFlat(True)
        self.btn_AlignLeft.setObjectName("btn_AlignLeft")
        self.horizontalLayout_2.addWidget(self.btn_AlignLeft)
        self.btn_AlignCenter = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_AlignCenter.setCheckable(True)
        self.btn_AlignCenter.setAutoExclusive(True)
        self.btn_AlignCenter.setFlat(True)
        self.btn_AlignCenter.setObjectName("btn_AlignCenter")
        self.horizontalLayout_2.addWidget(self.btn_AlignCenter)
        self.btn_AlignRight = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_AlignRight.setCheckable(True)
        self.btn_AlignRight.setAutoExclusive(True)
        self.btn_AlignRight.setFlat(True)
        self.btn_AlignRight.setObjectName("btn_AlignRight")
        self.horizontalLayout_2.addWidget(self.btn_AlignRight)
        self.lineEdit_Input = QtWidgets.QLineEdit(Form)
        self.lineEdit_Input.setGeometry(QtCore.QRect(20, 190, 291, 81))
        self.lineEdit_Input.setObjectName("lineEdit_Input")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(30, 160, 281, 18))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox = QtWidgets.QCheckBox(self.widget)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_3.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_3.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_3.addWidget(self.checkBox_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "GroupBox"))
        self.btn_FontBold.setText(_translate("Form", "粗体"))
        self.btn_FontItalic.setText(_translate("Form", "斜体"))
        self.btn_FontUnderLine.setText(_translate("Form", "下划线"))
        self.groupBox_2.setTitle(_translate("Form", "GroupBox"))
        self.btn_AlignLeft.setText(_translate("Form", "居左"))
        self.btn_AlignCenter.setText(_translate("Form", "居中"))
        self.btn_AlignRight.setText(_translate("Form", "居右"))
        self.checkBox.setText(_translate("Form", "Readonly"))
        self.checkBox_2.setText(_translate("Form", "Enabled"))
        self.checkBox_3.setText(_translate("Form", "ClearButtonEnabled"))
